version: "3.9"
services:
  eureka-service:
    image: eureka-server:latest
    ports:
      - "8082:8082"
    depends_on:
      - kafka-server
    networks:
      - microservice-network

  organization-service:
    image: organization-service:latest
    ports:
      - "8083:8083"
    depends_on:
      eureka-service:
        condition: service_started
    networks:
      - microservice-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    networks:
      - microservice-network

  kafka-server:
    image: wurstmeister/kafka:latest
    hostname: kafka
    ports:
      - 9092-9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=organization-events:1:1
    depends_on:
      - zookeeper
    networks:
      - microservice-network

networks:
  microservice-network:
