version: "3.9"
services:
  database:
    image: mysql:latest
    container_name: mysql-dev
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=microservice-db
    ports:
      - "3306:3306"
    networks:
      - microservice-network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - microservice-network

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - microservice-network

  kafka:
    image: bitnami/kafka:latest
    ports: 
      - 9093:9093
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092, EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    networks:
      - microservice-network
    depends_on:
      - zookeeper

  eureka-service:
    image: eureka-server:latest
    environment:
      - "SPRING.PROFILES.ACTIVE=docker"
    ports:
      - "8082:8082"
    depends_on:
      - zipkin
    networks:
      - microservice-network

  
  organization-service:
    image: organization-service:latest
    environment:
      - SPRING.PROFILES.ACTIVE=docker
      - SPRING.DATASOURCE.USERNAME=root
      - SPRING.DATASOURCE.PASSWORD=admin123
    ports:
      - "8083:8083"
    depends_on:
      - eureka-service
      - database
      - zipkin
      - kafka
    networks:
      - microservice-network

  license-service:
    image: licensing-service:latest
    environment:
      - SPRING.PROFILES.ACTIVE=docker
      - SPRING.DATASOURCE.USERNAME=root
      - SPRING.DATASOURCE.PASSWORD=admin123
    ports:
      - "8081:8081"
    depends_on:
      - eureka-service
      - database
      - zipkin
      - kafka
    networks:
      - microservice-network

networks:
  microservice-network:
