version: "3.9"
services:
  eureka-service:
    image: eureka-server:latest
    ports:
      - "8082:8082"
    networks:
      - microservice-network

  organization-service:
    image: organization-service:latest
    ports:
      - "8083:8083"
    depends_on:
      eureka-service:
        condition: service_started
    networks:
      - microservice-network

  license-service:
    image: licensing-service:latest
    ports:
      - "8081:8081"
    depends_on:
      eureka-service:
        condition: service_started
    networks:
      - microservice-network

networks:
  microservice-network:
